"use client";

import { Eye, Loader2, Pencil, Plus, RefreshCw, Search, Trash2 } from "lucide-react";
import { FormEvent, useCallback, useEffect, useMemo, useState } from "react";

import { DetailGrid, EmptyRow, Field, GlobalSpinStyle, LoadingRow, Message, Modal, TextAreaField } from "@/components/RealUi";
import { RequirePermission } from "@/components/RequirePermission";
import { CurrentUser, apiFetch, getCurrentUser } from "@/lib/api";

type History={shipment_id:string;shipment_number:string;shipment_status:string;shipment_container_id:string;seal_number:string|null;actual_cbm:number|string|null;container_status:string};
type ContainerRow={id:string;business_unit_id:string;container_number:string;container_type:string|null;tare_weight_kg:number|string|null;max_cbm:number|string|null;notes:string|null;current_shipment_count:number;item_count:number;total_quantity:number|string;shipment_history:History[];created_at:string};
type ListResponse={total:number;offset:number;limit:number;items:ContainerRow[]};
const empty={container_number:"",container_type:"",tare_weight_kg:"",max_cbm:"",notes:""};

function ContainersPage(){
 const [rows,setRows]=useState<ContainerRow[]>([]);const [search,setSearch]=useState("");const [loading,setLoading]=useState(true);const [error,setError]=useState("");const [success,setSuccess]=useState("");const [mode,setMode]=useState<"create"|"view"|"edit"|null>(null);const [selected,setSelected]=useState<ContainerRow|null>(null);const [form,setForm]=useState(empty);const [saving,setSaving]=useState(false);const [user,setUser]=useState<CurrentUser|null>(null);
 const isManager=useMemo(()=>{const r=new Set((user?.roles||[]).map(x=>x.toLowerCase()));return r.has("manager")||r.has("administrator")},[user]);
 const load=useCallback(async()=>{setLoading(true);try{const p=new URLSearchParams();if(search.trim())p.set("search",search.trim());p.set("limit","300");const r=await apiFetch<ListResponse>(`/containers?${p}`);setRows(r.items)}catch(e:any){setError(e?.message||"Unable to load containers.")}finally{setLoading(false)}},[search]);
 useEffect(()=>{getCurrentUser().then(setUser).catch(()=>{})},[]);useEffect(()=>{const t=setTimeout(load,250);return()=>clearTimeout(t)},[load]);
 function setField(k:keyof typeof empty,v:string){setForm(f=>({...f,[k]:v}))}
 function create(){setSelected(null);setForm(empty);setMode("create")}
 async function open(row:ContainerRow,target:"view"|"edit"){setMode(target);try{const d=await apiFetch<ContainerRow>(`/containers/${row.id}`);setSelected(d);setForm({container_number:d.container_number,container_type:d.container_type||"",tare_weight_kg:d.tare_weight_kg!=null?String(d.tare_weight_kg):"",max_cbm:d.max_cbm!=null?String(d.max_cbm):"",notes:d.notes||""})}catch(e:any){setError(e?.message||"Unable to load container.");setMode(null)}}
 async function save(e:FormEvent){e.preventDefault();setSaving(true);setError("");const payload={container_number:form.container_number,container_type:form.container_type||null,tare_weight_kg:form.tare_weight_kg?Number(form.tare_weight_kg):null,max_cbm:form.max_cbm?Number(form.max_cbm):null,notes:form.notes||null};try{if(mode==="create"){await apiFetch("/containers",{method:"POST",body:JSON.stringify(payload)});setSuccess("Container created.")}else if(selected){await apiFetch(`/containers/${selected.id}`,{method:"PUT",body:JSON.stringify(payload)});setSuccess("Container updated.")}await load();setMode(null)}catch(e:any){setError(e?.message||"Unable to save container.")}finally{setSaving(false)}}
 async function remove(row:ContainerRow){if(!confirm(`Delete unused container ${row.container_number}?`))return;try{await apiFetch(`/containers/${row.id}`,{method:"DELETE"});setSuccess("Container deleted.");await load()}catch(e:any){setError(e?.message||"Container cannot be deleted.")}}
 return <><div className="page-header"><div><div className="eyebrow">Logistics</div><h1 className="page-title">Containers</h1><p className="page-copy">Container master records and shipment history.</p></div><div style={{display:"flex",gap:8}}><button className="btn btn-secondary" onClick={load}><RefreshCw size={15}/>Refresh</button><button className="btn btn-primary" onClick={create}><Plus size={15}/>Add Container</button></div></div><Message error={error} success={success}/><div className="records-toolbar card"><div><strong>All Containers</strong><div className="muted" style={{fontSize:12}}>{rows.length} visible</div></div><div className="records-search"><Search size={15}/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Container number or type..."/></div></div><div className="table-wrap"><table><thead><tr><th>Container</th><th>Type</th><th>Max CBM</th><th>Shipments</th><th>Items</th><th>Total Qty</th><th>Actions</th></tr></thead><tbody>{loading?<LoadingRow columns={7}/>:rows.length===0?<EmptyRow columns={7}/>:rows.map(r=><tr key={r.id}><td><strong>{r.container_number}</strong></td><td>{r.container_type||"—"}</td><td>{r.max_cbm??"—"}</td><td>{r.current_shipment_count}</td><td>{r.item_count}</td><td>{Number(r.total_quantity)}</td><td><div className="record-actions"><button className="record-action view" onClick={()=>open(r,"view")}><Eye size={14}/></button><button className="record-action edit" onClick={()=>open(r,"edit")}><Pencil size={14}/></button>{isManager&&r.current_shipment_count===0&&<button className="record-action delete" onClick={()=>remove(r)}><Trash2 size={14}/></button>}</div></td></tr>)}</tbody></table></div>
 {(mode==="create"||mode==="edit")&&<Modal title={mode==="create"?"Add Container":`Edit ${selected?.container_number||"Container"}`} eyebrow="Logistics" onClose={()=>setMode(null)}><form onSubmit={save}><div className="form-grid"><Field label="Container Number" value={form.container_number} onChange={v=>setField("container_number",v)} required/><Field label="Container Type" value={form.container_type} onChange={v=>setField("container_type",v)} placeholder="40HC, 20GP..."/><Field label="Tare Weight (kg)" type="number" min="0" step="0.01" value={form.tare_weight_kg} onChange={v=>setField("tare_weight_kg",v)}/><Field label="Max CBM" type="number" min="0" step="0.01" value={form.max_cbm} onChange={v=>setField("max_cbm",v)}/><TextAreaField label="Notes" value={form.notes} onChange={v=>setField("notes",v)}/></div><div style={{display:"flex",justifyContent:"flex-end",gap:8,marginTop:18}}><button type="button" className="btn btn-secondary" onClick={()=>setMode(null)}>Cancel</button><button className="btn btn-primary" disabled={saving}>{saving?<><Loader2 className="spin" size={15}/>Saving...</>:"Save Container"}</button></div></form></Modal>}
 {mode==="view"&&selected&&<Modal title={selected.container_number} eyebrow="Container Details" onClose={()=>setMode(null)} width={900}><DetailGrid rows={[["Type",selected.container_type||"—"],["Tare Weight",selected.tare_weight_kg??"—"],["Max CBM",selected.max_cbm??"—"],["Items",selected.item_count],["Total Quantity",Number(selected.total_quantity)],["Notes",selected.notes||"—"]]}/><div className="panel-head" style={{marginTop:22}}><h3>Shipment History</h3></div><div className="table-wrap"><table><thead><tr><th>Shipment</th><th>Shipment Status</th><th>Container Status</th><th>Seal</th><th>CBM</th></tr></thead><tbody>{selected.shipment_history.length===0?<EmptyRow columns={5} text="No shipment history."/>:selected.shipment_history.map(h=><tr key={h.shipment_container_id}><td>{h.shipment_number}</td><td>{h.shipment_status}</td><td>{h.container_status}</td><td>{h.seal_number||"—"}</td><td>{h.actual_cbm??"—"}</td></tr>)}</tbody></table></div></Modal>}
 <GlobalSpinStyle/></>;
}

export default function Page() {
  return (
    <RequirePermission perm="containers.view">
      <ContainersPage />
    </RequirePermission>
  );
}
