"use client";

import { keepPreviousData, useQuery, useQueryClient } from "@tanstack/react-query";
import { Eye, Loader2, Pencil, Plus, RefreshCw, Search, Trash2, UserPlus } from "lucide-react";
import { FormEvent, useEffect, useMemo, useState } from "react";

import { DetailGrid, EmptyRow, Field, GlobalSpinStyle, LoadingRow, Message, Modal, StatusBadge, TextAreaField, money } from "@/components/RealUi";
import { RequirePermission } from "@/components/RequirePermission";
import { apiFetch } from "@/lib/api";
import { useCurrentUser } from "@/lib/hooks/useCurrentUser";
import { invalidate } from "@/lib/invalidate";
import { queryKeys } from "@/lib/queryKeys";

type Contact={id:string;full_name:string;role_title:string|null;email:string|null;phone:string|null;whatsapp_wechat:string|null;is_primary:boolean;notes:string|null;created_at:string};
type Supplier={id:string;supplier_number:string|null;name:string;company_name:string|null;main_email:string|null;main_phone:string|null;whatsapp_wechat:string|null;address_line1:string|null;address_line2:string|null;city:string|null;state_region:string|null;postal_code:string|null;country_code:string|null;payment_terms:string|null;rating:number|string|null;notes:string|null;is_active:boolean;outstanding_balance:number|string;purchase_order_count:number;contacts:Contact[];created_at:string;updated_at:string};
type ListResponse={total:number;offset:number;limit:number;items:Supplier[]};
type SupplierPO={id:string;po_number:string;order_date:string|null;expected_delivery:string|null;status:string;order_total:number|string;paid_amount:number|string;balance_due:number|string;payment_status:string};
type Quote={id:string;quote_number:string;quote_date:string|null;valid_until:string|null;status:string;currency_code:string;notes:string|null};

const empty={name:"",company_name:"",main_email:"",main_phone:"",whatsapp_wechat:"",address_line1:"",address_line2:"",city:"",state_region:"",postal_code:"",country_code:"",payment_terms:"",rating:"",notes:""};

function SuppliersPage(){
  const queryClient=useQueryClient();
  const { data: user } = useCurrentUser();
  const [search,setSearch]=useState("");const [debouncedSearch,setDebouncedSearch]=useState("");const [activeOnly,setActiveOnly]=useState(true);const [error,setError]=useState("");const [success,setSuccess]=useState("");const [mode,setMode]=useState<"create"|"view"|"edit"|null>(null);const [selected,setSelected]=useState<Supplier|null>(null);const [form,setForm]=useState(empty);const [saving,setSaving]=useState(false);const [orders,setOrders]=useState<SupplierPO[]>([]);const [quotes,setQuotes]=useState<Quote[]>([]);
  const isManager=useMemo(()=>{const r=new Set((user?.roles||[]).map(x=>x.toLowerCase()));return r.has("manager")||r.has("administrator")},[user]);
  useEffect(()=>{const t=setTimeout(()=>setDebouncedSearch(search),250);return()=>clearTimeout(t)},[search]);
  const listParams=useMemo(()=>({search:debouncedSearch.trim()||undefined,active_only:activeOnly}),[debouncedSearch,activeOnly]);
  const suppliersQuery=useQuery({
    queryKey:queryKeys.suppliers.list(listParams),
    queryFn:()=>{const p=new URLSearchParams();if(listParams.search)p.set("search",listParams.search);p.set("active_only",String(listParams.active_only));p.set("limit","300");return apiFetch<ListResponse>(`/suppliers?${p}`);},
    staleTime:5*60*1000,gcTime:15*60*1000,placeholderData:keepPreviousData,
  });
  const rows=suppliersQuery.data?.items??[];
  const loading=suppliersQuery.isLoading;
  const load=()=>suppliersQuery.refetch();
  function setField(k:keyof typeof empty,v:string){setForm(f=>({...f,[k]:v}))}
  function create(){setSelected(null);setForm(empty);setMode("create");setError("")}
  async function open(row:Supplier,target:"view"|"edit"){setMode(target);try{const d=await apiFetch<Supplier>(`/suppliers/${row.id}`);setSelected(d);setForm({name:d.name,company_name:d.company_name||"",main_email:d.main_email||"",main_phone:d.main_phone||"",whatsapp_wechat:d.whatsapp_wechat||"",address_line1:d.address_line1||"",address_line2:d.address_line2||"",city:d.city||"",state_region:d.state_region||"",postal_code:d.postal_code||"",country_code:d.country_code||"",payment_terms:d.payment_terms||"",rating:d.rating!=null?String(d.rating):"",notes:d.notes||""});if(target==="view"){const [po,q]=await Promise.all([apiFetch<SupplierPO[]>(`/suppliers/${row.id}/purchase-orders`),apiFetch<Quote[]>(`/suppliers/${row.id}/quotes`)]);setOrders(po);setQuotes(q)}}catch(e:any){setError(e?.message||"Unable to load supplier.");setMode(null)}}
  async function save(e:FormEvent){e.preventDefault();setSaving(true);setError("");const payload={name:form.name,company_name:form.company_name||null,main_email:form.main_email||null,main_phone:form.main_phone||null,whatsapp_wechat:form.whatsapp_wechat||null,address_line1:form.address_line1||null,address_line2:form.address_line2||null,city:form.city||null,state_region:form.state_region||null,postal_code:form.postal_code||null,country_code:form.country_code?form.country_code.toUpperCase():null,payment_terms:form.payment_terms||null,rating:form.rating?Number(form.rating):null,notes:form.notes||null};try{if(mode==="create"){await apiFetch("/suppliers",{method:"POST",body:JSON.stringify({...payload,contacts:[]})});setSuccess("Supplier created.")}else if(selected){await apiFetch(`/suppliers/${selected.id}`,{method:"PUT",body:JSON.stringify(payload)});setSuccess("Supplier updated.")}await invalidate(queryClient,["suppliers","dashboard"]);setMode(null)}catch(e:any){setError(e?.message||"Unable to save supplier.")}finally{setSaving(false)}}
  async function deactivate(s:Supplier){if(!confirm(`Deactivate ${s.name}?`))return;try{await apiFetch(`/suppliers/${s.id}`,{method:"DELETE"});setSuccess("Supplier deactivated.");await invalidate(queryClient,["suppliers","dashboard"])}catch(e:any){setError(e?.message||"Unable to deactivate supplier.")}}
  async function addContact(){if(!selected)return;const full_name=prompt("Contact full name");if(!full_name)return;const email=prompt("Email","");const phone=prompt("Phone","");try{await apiFetch(`/suppliers/${selected.id}/contacts`,{method:"POST",body:JSON.stringify({full_name,email:email||null,phone:phone||null,is_primary:selected.contacts.length===0,notes:null})});await open(selected,"view")}catch(e:any){setError(e?.message||"Unable to add contact.")}}
  async function editContact(c:Contact){if(!selected)return;const role=prompt("Role / title",c.role_title||"");if(role===null)return;const phone=prompt("Phone",c.phone||"");try{await apiFetch(`/suppliers/${selected.id}/contacts/${c.id}`,{method:"PUT",body:JSON.stringify({role_title:role||null,phone:phone||null})});await open(selected,"view")}catch(e:any){setError(e?.message||"Unable to edit contact.")}}
  async function deleteContact(c:Contact){if(!selected||!confirm(`Delete ${c.full_name}?`))return;try{await apiFetch(`/suppliers/${selected.id}/contacts/${c.id}`,{method:"DELETE"});await open(selected,"view")}catch(e:any){setError(e?.message||"Unable to delete contact.")}}

  return <><div className="page-header"><div><div className="eyebrow">Procurement</div><h1 className="page-title">Suppliers</h1><p className="page-copy">Live suppliers, contacts, balances and sourcing history.</p></div><div style={{display:"flex",gap:8}}><button className="btn btn-secondary" onClick={load}><RefreshCw size={15}/>Refresh</button><button className="btn btn-primary" onClick={create}><Plus size={15}/>Add Supplier</button></div></div><Message error={error||(suppliersQuery.isError?"Unable to load suppliers.":"")} success={success}/>
  <div className="records-toolbar card"><div><strong>Supplier Directory</strong><div className="muted" style={{fontSize:12}}>{rows.length} visible</div></div><div style={{display:"flex",gap:8,alignItems:"center"}}><div className="records-search"><Search size={15}/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Name, company, email..."/></div><label className="badge"><input type="checkbox" checked={activeOnly} onChange={e=>setActiveOnly(e.target.checked)}/> Active only</label></div></div>
  <div className="table-wrap"><table><thead><tr><th>Supplier</th><th>Company</th><th>Contact</th><th>Terms</th><th>Rating</th><th>POs</th><th>Outstanding</th><th>Status</th><th>Actions</th></tr></thead><tbody>{loading?<LoadingRow columns={9}/>:rows.length===0?<EmptyRow columns={9}/>:rows.map(s=><tr key={s.id}><td><strong>{s.name}</strong><div className="muted" style={{fontSize:11}}>{s.supplier_number||""}</div></td><td>{s.company_name||"—"}</td><td>{s.main_email||s.main_phone||"—"}</td><td>{s.payment_terms||"—"}</td><td>{s.rating??"—"}</td><td>{s.purchase_order_count}</td><td>{money(s.outstanding_balance)}</td><td><StatusBadge value={s.is_active?"active":"inactive"}/></td><td><div className="record-actions"><button className="record-action view" onClick={()=>open(s,"view")}><Eye size={14}/></button><button className="record-action edit" onClick={()=>open(s,"edit")}><Pencil size={14}/></button>{isManager&&s.is_active&&<button className="record-action delete" onClick={()=>deactivate(s)}><Trash2 size={14}/></button>}</div></td></tr>)}</tbody></table></div>
  {(mode==="create"||mode==="edit")&&<Modal title={mode==="create"?"Add Supplier":`Edit ${selected?.name||"Supplier"}`} eyebrow="Supplier" onClose={()=>setMode(null)}><form onSubmit={save}><div className="form-grid"><Field label="Name" value={form.name} onChange={v=>setField("name",v)} required/><Field label="Company" value={form.company_name} onChange={v=>setField("company_name",v)}/><Field label="Email" type="email" value={form.main_email} onChange={v=>setField("main_email",v)}/><Field label="Phone" value={form.main_phone} onChange={v=>setField("main_phone",v)}/><Field label="WhatsApp / WeChat" value={form.whatsapp_wechat} onChange={v=>setField("whatsapp_wechat",v)}/><Field label="Payment Terms" value={form.payment_terms} onChange={v=>setField("payment_terms",v)}/><Field label="Rating 0–5" type="number" min="0" max="5" step="0.1" value={form.rating} onChange={v=>setField("rating",v)}/><Field label="Country Code" value={form.country_code} onChange={v=>setField("country_code",v)}/><Field label="Address" value={form.address_line1} onChange={v=>setField("address_line1",v)}/><Field label="Address Line 2" value={form.address_line2} onChange={v=>setField("address_line2",v)}/><Field label="City" value={form.city} onChange={v=>setField("city",v)}/><Field label="State / Region" value={form.state_region} onChange={v=>setField("state_region",v)}/><Field label="Postal Code" value={form.postal_code} onChange={v=>setField("postal_code",v)}/><TextAreaField label="Notes" value={form.notes} onChange={v=>setField("notes",v)}/></div><div style={{display:"flex",justifyContent:"flex-end",gap:8,marginTop:18}}><button type="button" className="btn btn-secondary" onClick={()=>setMode(null)}>Cancel</button><button className="btn btn-primary" disabled={saving}>{saving?<><Loader2 size={15} className="spin"/>Saving...</>:"Save Supplier"}</button></div></form></Modal>}
  {mode==="view"&&selected&&<Modal title={selected.name} eyebrow="Supplier Details" onClose={()=>setMode(null)} width={1000}><DetailGrid rows={[["Supplier Number",selected.supplier_number||"—"],["Company",selected.company_name||"—"],["Email",selected.main_email||"—"],["Phone",selected.main_phone||"—"],["Payment Terms",selected.payment_terms||"—"],["Rating",selected.rating??"—"],["Outstanding",money(selected.outstanding_balance)],["Status",<StatusBadge value={selected.is_active?"active":"inactive"}/>],["Notes",selected.notes||"—"]]}/><div className="panel-head" style={{marginTop:22}}><h3>Contacts</h3><button className="btn btn-secondary" onClick={addContact}><UserPlus size={14}/>Add Contact</button></div>{selected.contacts.length===0?<div className="muted">No contacts.</div>:<div style={{display:"grid",gap:8}}>{selected.contacts.map(c=><div key={c.id} className="card" style={{padding:12,display:"flex",alignItems:"center",gap:12}}><div style={{flex:1}}><strong>{c.full_name}{c.is_primary?" · Primary":""}</strong><div className="muted" style={{fontSize:12}}>{[c.role_title,c.email,c.phone].filter(Boolean).join(" · ")}</div></div><button className="record-action edit" onClick={()=>editContact(c)}><Pencil size={14}/></button><button className="record-action delete" onClick={()=>deleteContact(c)}><Trash2 size={14}/></button></div>)}</div>}<div className="panel-head" style={{marginTop:22}}><h3>Purchase Orders</h3></div><div className="table-wrap"><table><thead><tr><th>PO</th><th>Status</th><th>Total</th><th>Balance</th></tr></thead><tbody>{orders.length===0?<EmptyRow columns={4} text="No purchase orders."/>:orders.map(p=><tr key={p.id}><td>{p.po_number}</td><td><StatusBadge value={p.status}/></td><td>{money(p.order_total)}</td><td>{money(p.balance_due)}</td></tr>)}</tbody></table></div><div className="panel-head" style={{marginTop:22}}><h3>Quotes</h3></div>{quotes.length===0?<div className="muted">No quotes.</div>:quotes.map(q=><div className="card" style={{padding:10,marginBottom:8}} key={q.id}><strong>{q.quote_number}</strong> · {q.status}</div>)}</Modal>}
  <GlobalSpinStyle/></>;
}

export default function Page() {
  return (
    <RequirePermission perm="suppliers.view">
      <SuppliersPage />
    </RequirePermission>
  );
}
