"use client";

import { keepPreviousData, useQuery, useQueryClient } from "@tanstack/react-query";
import { Archive, Eye, Loader2, Pencil, Plus, RefreshCw, Search } from "lucide-react";
import { FormEvent, useEffect, useMemo, useRef, useState } from "react";

import { DetailGrid, EmptyRow, Field, GlobalSpinStyle, LoadingRow, Message, Modal, SelectField, StatusBadge, TextAreaField, labelize, money } from "@/components/RealUi";
import { RequirePermission } from "@/components/RequirePermission";
import { apiFetch } from "@/lib/api";
import { useCurrentUser } from "@/lib/hooks/useCurrentUser";
import { invalidate } from "@/lib/invalidate";
import { queryKeys } from "@/lib/queryKeys";

type NewItem={id:string;item_code:string;sku:string|null;name:string;description:string|null;category_id:string|null;category_name:string|null;condition:string|null;inventory_status:string;default_cost:number|string|null;default_selling_price:number|string|null;minimum_selling_price:number|string|null;currency_code:string;barcode_qr:string|null;notes:string|null;brand:string|null;specifications:Record<string,unknown>;quantity_on_hand:number|string;quantity_reserved:number|string;quantity_available:number|string;storage_location_id:string|null;location_code:string|null;created_at:string;updated_at:string};
type ListResponse={total:number;offset:number;limit:number;items:NewItem[]};
type Category={id:string;name:string;applies_to:string|null};
type Location={id:string;location_code:string;name:string|null};
const statuses=["draft","incoming","in_stock","to_photograph","ready_to_list","listed","reserved","on_hold","sold","scrapped","archived"];
const empty={item_code:"",sku:"",name:"",description:"",category_id:"",condition:"New",inventory_status:"draft",default_cost:"",default_selling_price:"",minimum_selling_price:"",barcode_qr:"",notes:"",brand:"",specifications:"{}",storage_location_id:"",quantity_on_hand:"0",average_unit_cost:""};

function NewItemsPage(){
 const queryClient=useQueryClient();
 const { data: user } = useCurrentUser();
 const [search,setSearch]=useState("");const [debouncedSearch,setDebouncedSearch]=useState("");const [statusFilter,setStatusFilter]=useState("");const [categoryFilter,setCategoryFilter]=useState("");const [includeArchived,setIncludeArchived]=useState(false);const [error,setError]=useState("");const [success,setSuccess]=useState("");const [mode,setMode]=useState<"create"|"view"|"edit"|null>(null);const [selected,setSelected]=useState<NewItem|null>(null);const [form,setForm]=useState(empty);const [saving,setSaving]=useState(false);
 const isManager=useMemo(()=>{const r=new Set((user?.roles||[]).map(x=>x.toLowerCase()));return r.has("manager")||r.has("administrator")},[user]);
 useEffect(()=>{const t=setTimeout(()=>setDebouncedSearch(search),250);return()=>clearTimeout(t)},[search]);
 const listParams=useMemo(()=>({search:debouncedSearch.trim()||undefined,inventory_status:statusFilter||undefined,category_id:categoryFilter||undefined,include_archived:includeArchived}),[debouncedSearch,statusFilter,categoryFilter,includeArchived]);
 const itemsQuery=useQuery({
   queryKey:queryKeys.newItems.list(listParams),
   queryFn:()=>{const p=new URLSearchParams();if(listParams.search)p.set("search",listParams.search);if(listParams.inventory_status)p.set("inventory_status",listParams.inventory_status);if(listParams.category_id)p.set("category_id",listParams.category_id);p.set("include_archived",String(listParams.include_archived));p.set("limit","300");return apiFetch<ListResponse>(`/new-items?${p}`);},
   staleTime:3*60*1000,gcTime:10*60*1000,placeholderData:keepPreviousData,
 });
 const rows=itemsQuery.data?.items??[];
 const loading=itemsQuery.isLoading;
 const load=()=>itemsQuery.refetch();
 const categoriesQuery=useQuery({queryKey:queryKeys.newItems.categories(),queryFn:()=>apiFetch<Category[]>("/new-items/lookups/categories"),staleTime:10*60*1000});
 const categories=categoriesQuery.data??[];
 const locationsQuery=useQuery({queryKey:queryKeys.newItems.locations(),queryFn:()=>apiFetch<Location[]>("/new-items/lookups/storage-locations"),staleTime:5*60*1000});
 const locations=locationsQuery.data??[];
 const autoOpenedRef=useRef(false);
 useEffect(()=>{
   if(autoOpenedRef.current)return;
   if(new URLSearchParams(window.location.search).get("action")==="add"){
     autoOpenedRef.current=true;create();
   }
 },[]);
 function setField(k:keyof typeof empty,v:string){setForm(f=>({...f,[k]:v}))}
 function create(){setSelected(null);setForm(empty);setMode("create");setError("")}
 async function open(row:NewItem,target:"view"|"edit"){setMode(target);try{const d=await apiFetch<NewItem>(`/new-items/${row.id}`);setSelected(d);setForm({item_code:d.item_code,sku:d.sku||"",name:d.name,description:d.description||"",category_id:d.category_id||"",condition:d.condition||"New",inventory_status:d.inventory_status,default_cost:d.default_cost!=null?String(d.default_cost):"",default_selling_price:d.default_selling_price!=null?String(d.default_selling_price):"",minimum_selling_price:d.minimum_selling_price!=null?String(d.minimum_selling_price):"",barcode_qr:d.barcode_qr||"",notes:d.notes||"",brand:d.brand||"",specifications:JSON.stringify(d.specifications||{},null,2),storage_location_id:d.storage_location_id||"",quantity_on_hand:String(d.quantity_on_hand||0),average_unit_cost:d.default_cost!=null?String(d.default_cost):""})}catch(e:any){setError(e?.message||"Unable to load new item.");setMode(null)}}
 async function save(e:FormEvent){e.preventDefault();setSaving(true);setError("");let specs:Record<string,unknown>={};try{specs=form.specifications.trim()?JSON.parse(form.specifications):{}}catch{setError("Specifications must be valid JSON, for example {\"material\":\"steel\"}.");setSaving(false);return}const common={item_code:form.item_code||null,sku:form.sku||null,name:form.name,description:form.description||null,category_id:form.category_id||null,condition:form.condition||null,inventory_status:form.inventory_status,default_cost:form.default_cost?Number(form.default_cost):null,default_selling_price:form.default_selling_price?Number(form.default_selling_price):null,minimum_selling_price:form.minimum_selling_price?Number(form.minimum_selling_price):null,barcode_qr:form.barcode_qr||null,notes:form.notes||null,brand:form.brand||null,specifications:specs};try{if(mode==="create"){await apiFetch("/new-items",{method:"POST",body:JSON.stringify({...common,storage_location_id:form.storage_location_id||null,quantity_on_hand:Number(form.quantity_on_hand||0),average_unit_cost:form.average_unit_cost?Number(form.average_unit_cost):null})});setSuccess("New item created.")}else if(selected){await apiFetch(`/new-items/${selected.id}`,{method:"PUT",body:JSON.stringify(common)});setSuccess("New item updated.")}await invalidate(queryClient,["newItems","inventory","dashboard"]);setMode(null)}catch(e:any){setError(e?.message||"Unable to save new item.")}finally{setSaving(false)}}
 async function archive(row:NewItem){if(!confirm(`Archive ${row.name}? Reserved stock must be released first.`))return;try{await apiFetch(`/new-items/${row.id}`,{method:"DELETE"});setSuccess("New item archived.");await invalidate(queryClient,["newItems","inventory","dashboard"])}catch(e:any){setError(e?.message||"Unable to archive new item.")}}
 return <><div className="page-header"><div><div className="eyebrow">Catalog</div><h1 className="page-title">New Items</h1><p className="page-copy">Live new-product catalog and inventory status.</p></div><div style={{display:"flex",gap:8}}><button className="btn btn-secondary" onClick={load}><RefreshCw size={15}/>Refresh</button><button className="btn btn-primary" onClick={create}><Plus size={15}/>Add New Item</button></div></div><Message error={error||(itemsQuery.isError?"Unable to load new items.":"")} success={success}/><div className="records-toolbar card"><div><strong>New Item Catalog</strong><div className="muted" style={{fontSize:12}}>{rows.length} visible</div></div><div style={{display:"flex",gap:8,flexWrap:"wrap"}}><div className="records-search"><Search size={15}/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Item, SKU, brand..."/></div><select className="select" style={{width:160}} value={categoryFilter} onChange={e=>setCategoryFilter(e.target.value)}><option value="">All categories</option>{categories.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select><select className="select" style={{width:160}} value={statusFilter} onChange={e=>setStatusFilter(e.target.value)}><option value="">All statuses</option>{statuses.map(s=><option key={s} value={s}>{labelize(s)}</option>)}</select><label className="badge"><input type="checkbox" checked={includeArchived} onChange={e=>setIncludeArchived(e.target.checked)}/> Archived</label></div></div><div className="table-wrap"><table><thead><tr><th>Item</th><th>Brand</th><th>Category</th><th>Available</th><th>Location</th><th>Cost</th><th>Price</th><th>Status</th><th>Actions</th></tr></thead><tbody>{loading?<LoadingRow columns={9}/>:rows.length===0?<EmptyRow columns={9}/>:rows.map(r=><tr key={r.id}><td><strong>{r.name}</strong><div className="muted" style={{fontSize:11}}>{r.item_code}{r.sku?` · ${r.sku}`:""}</div></td><td>{r.brand||"—"}</td><td>{r.category_name||"—"}</td><td>{Number(r.quantity_available)}</td><td>{r.location_code||"—"}</td><td>{money(r.default_cost,r.currency_code)}</td><td>{money(r.default_selling_price,r.currency_code)}</td><td><StatusBadge value={r.inventory_status}/></td><td><div className="record-actions"><button className="record-action view" onClick={()=>open(r,"view")}><Eye size={14}/></button><button className="record-action edit" onClick={()=>open(r,"edit")}><Pencil size={14}/></button>{isManager&&r.inventory_status!=="archived"&&<button className="record-action delete" onClick={()=>archive(r)}><Archive size={14}/></button>}</div></td></tr>)}</tbody></table></div>
 {(mode==="create"||mode==="edit")&&<Modal title={mode==="create"?"Add New Item":`Edit ${selected?.name||"Item"}`} eyebrow="Catalog" onClose={()=>setMode(null)}><form onSubmit={save}><div className="form-grid"><Field label="Name" value={form.name} onChange={v=>setField("name",v)} required/><Field label="Item Code" value={form.item_code} onChange={v=>setField("item_code",v)} placeholder="Auto-generated if blank"/><Field label="SKU" value={form.sku} onChange={v=>setField("sku",v)}/><Field label="Brand" value={form.brand} onChange={v=>setField("brand",v)}/><SelectField label="Category" value={form.category_id} onChange={v=>setField("category_id",v)} options={[{value:"",label:"Uncategorized"},...categories.map(c=>({value:c.id,label:c.name}))]}/><SelectField label="Status" value={form.inventory_status} onChange={v=>setField("inventory_status",v)} options={statuses.map(s=>({value:s,label:labelize(s)}))}/><Field label="Condition" value={form.condition} onChange={v=>setField("condition",v)}/><Field label="Default Cost" type="number" min="0" step="0.01" value={form.default_cost} onChange={v=>setField("default_cost",v)}/><Field label="Selling Price" type="number" min="0" step="0.01" value={form.default_selling_price} onChange={v=>setField("default_selling_price",v)}/><Field label="Minimum Price" type="number" min="0" step="0.01" value={form.minimum_selling_price} onChange={v=>setField("minimum_selling_price",v)}/><Field label="Barcode / QR" value={form.barcode_qr} onChange={v=>setField("barcode_qr",v)}/>{mode==="create"&&<><SelectField label="Initial Storage" value={form.storage_location_id} onChange={v=>setField("storage_location_id",v)} options={[{value:"",label:"Unassigned"},...locations.map(l=>({value:l.id,label:l.name?`${l.location_code} — ${l.name}`:l.location_code}))]}/><Field label="Initial Quantity" type="number" min="0" step="0.001" value={form.quantity_on_hand} onChange={v=>setField("quantity_on_hand",v)}/><Field label="Average Unit Cost" type="number" min="0" step="0.01" value={form.average_unit_cost} onChange={v=>setField("average_unit_cost",v)}/></>}<TextAreaField label="Description" value={form.description} onChange={v=>setField("description",v)}/><TextAreaField label="Specifications (JSON)" value={form.specifications} onChange={v=>setField("specifications",v)} placeholder='{"material":"steel"}'/><TextAreaField label="Notes" value={form.notes} onChange={v=>setField("notes",v)}/></div><div style={{display:"flex",justifyContent:"flex-end",gap:8,marginTop:18}}><button type="button" className="btn btn-secondary" onClick={()=>setMode(null)}>Cancel</button><button className="btn btn-primary" disabled={saving}>{saving?<><Loader2 className="spin" size={15}/>Saving...</>:"Save Item"}</button></div></form></Modal>}
 {mode==="view"&&selected&&<Modal title={selected.name} eyebrow="New Item Details" onClose={()=>setMode(null)} width={900}><DetailGrid rows={[["Item Code",selected.item_code],["SKU",selected.sku||"—"],["Brand",selected.brand||"—"],["Category",selected.category_name||"—"],["Status",<StatusBadge value={selected.inventory_status}/>],["On Hand",Number(selected.quantity_on_hand)],["Reserved",Number(selected.quantity_reserved)],["Available",Number(selected.quantity_available)],["Location",selected.location_code||"—"],["Cost",money(selected.default_cost,selected.currency_code)],["Selling Price",money(selected.default_selling_price,selected.currency_code)],["Specifications",<pre style={{whiteSpace:"pre-wrap",margin:0}}>{JSON.stringify(selected.specifications,null,2)}</pre>],["Description",selected.description||"—"],["Notes",selected.notes||"—"]]}/></Modal>}
 <GlobalSpinStyle/></>;
}

export default function Page() {
  return (
    <RequirePermission perm="new_items.view">
      <NewItemsPage />
    </RequirePermission>
  );
}
