"use client";

import { Eye, Pencil, Plus, RefreshCw, Trash2 } from "lucide-react";
import { useEffect, useMemo, useState } from "react";

import { DetailGrid, EmptyRow, GlobalSpinStyle, Message, Modal, StatusBadge, labelize, money } from "@/components/RealUi";
import { RequirePermission } from "@/components/RequirePermission";
import { CurrentUser, apiFetch, getCurrentUser } from "@/lib/api";

type Supplier={id:string;name:string};type Item={id:string;item_code:string;name:string};type POItem={id:string;purchase_order_id:string;po_number:string;item_id:string;item_name:string};type Employee={id:string;display_name:string};
type QuoteItem={id:string;item_id:string;item_code:string;item_name:string;moq:number|string|null;quoted_price:number|string|null;negotiated_price:number|string|null;notes:string|null};
type Quote={id:string;quote_number:string;supplier_id:string;supplier_name:string;quote_date:string|null;valid_until:string|null;currency_code:string;status:string;quotation_file_id:string|null;notes:string|null;items:QuoteItem[];created_at:string};
type QuoteList={total:number;items:Quote[]};
type Cert={id:string;supplier_id:string;supplier_name:string;certification_type:string;issue_date:string|null;expiry_date:string|null;status:string;document_file_id:string|null;notes:string|null};
type Prod={id:string;purchase_order_item_id:string|null;supplier_id:string|null;supplier_name:string|null;item_id:string|null;item_name:string|null;production_stage:string;start_date:string|null;estimated_completion:string|null;actual_completion:string|null;packaging_requirements:string|null;labeling_requirements:string|null;warranty_terms:string|null;spare_parts_included:string|null;certification_requirements:string|null;production_notes:string|null;production_issues:string|null;next_milestone:string|null;priority:string;created_at:string;updated_at:string};
type QC={id:string;inspection_number:string;inspection_date:string|null;inspector_employee_id:string|null;inspector_name:string|null;supplier_id:string|null;supplier_name:string|null;item_id:string|null;item_name:string|null;purchase_order_item_id:string|null;sample_approval_status:string|null;defects_found:string|null;qc_result:string|null;actions_required:string|null;resolution_deadline:string|null;follow_up_needed:boolean;inspection_notes:string|null;created_at:string;updated_at:string};
type Comm={id:string;supplier_id:string;supplier_name:string;occurred_at:string;channel:string|null;subject:string|null;notes:string|null;created_by_user_id:string|null;created_at:string};
type Tab="quotes"|"certifications"|"production"|"qc"|"communications";

function ProcurementPage(){
 const [tab,setTab]=useState<Tab>("quotes");const [quotes,setQuotes]=useState<Quote[]>([]);const [certs,setCerts]=useState<Cert[]>([]);const [production,setProduction]=useState<Prod[]>([]);const [qc,setQc]=useState<QC[]>([]);const [communications,setCommunications]=useState<Comm[]>([]);const [suppliers,setSuppliers]=useState<Supplier[]>([]);const [items,setItems]=useState<Item[]>([]);const [poItems,setPoItems]=useState<POItem[]>([]);const [employees,setEmployees]=useState<Employee[]>([]);const [user,setUser]=useState<CurrentUser|null>(null);const [error,setError]=useState("");const [success,setSuccess]=useState("");const [selectedQuote,setSelectedQuote]=useState<Quote|null>(null);
 const isManager=useMemo(()=>{const r=new Set((user?.roles||[]).map(x=>x.toLowerCase()));return r.has("manager")||r.has("administrator")},[user]);
 async function load(){setError("");try{const [q,c,p,qi,co,s,i,po,e,u]=await Promise.all([apiFetch<QuoteList>("/procurement-ops/quotes"),apiFetch<Cert[]>("/procurement-ops/certifications"),apiFetch<Prod[]>("/procurement-ops/production-runs"),apiFetch<QC[]>("/procurement-ops/qc-inspections"),apiFetch<Comm[]>("/procurement-ops/communications"),apiFetch<Supplier[]>("/procurement-ops/lookups/suppliers"),apiFetch<Item[]>("/procurement-ops/lookups/items"),apiFetch<POItem[]>("/procurement-ops/lookups/purchase-order-items"),apiFetch<Employee[]>("/procurement-ops/lookups/employees"),getCurrentUser()]);setQuotes(q.items);setCerts(c);setProduction(p);setQc(qi);setCommunications(co);setSuppliers(s);setItems(i);setPoItems(po);setEmployees(e);setUser(u)}catch(e:any){setError(e?.message||"Unable to load procurement operations.")}}
 useEffect(()=>{load()},[]);
 const supplierId=()=>prompt("Supplier ID",suppliers[0]?.id||"");const itemId=()=>prompt("Item ID",items[0]?.id||"");
 async function addQuote(){const sid=supplierId();if(!sid)return;const number=prompt("Quote number (blank = auto)","");const date=prompt("Quote date YYYY-MM-DD",new Date().toISOString().slice(0,10));try{await apiFetch("/procurement-ops/quotes",{method:"POST",body:JSON.stringify({quote_number:number||null,supplier_id:sid,quote_date:date||null,currency_code:"USD",status:"active",items:[]})});setSuccess("Supplier quote created.");await load()}catch(e:any){setError(e?.message||"Unable to create quote.")}}
 async function viewQuote(q:Quote){try{setSelectedQuote(await apiFetch<Quote>(`/procurement-ops/quotes/${q.id}`))}catch(e:any){setError(e?.message||"Unable to load quote.")}}
 async function editQuote(q:Quote){const st=prompt("Status: active, expired, accepted, rejected, superseded",q.status);if(!st)return;const notes=prompt("Notes",q.notes||"");try{await apiFetch(`/procurement-ops/quotes/${q.id}`,{method:"PUT",body:JSON.stringify({status:st,notes:notes||null})});setSuccess("Quote updated.");await load()}catch(e:any){setError(e?.message||"Unable to update quote.")}}
 async function addQuoteItem(){if(!selectedQuote)return;const iid=itemId();if(!iid)return;const price=Number(prompt("Quoted price","0")||0);const moq=Number(prompt("MOQ","1")||0);try{await apiFetch(`/procurement-ops/quotes/${selectedQuote.id}/items`,{method:"POST",body:JSON.stringify({item_id:iid,moq,quoted_price:price,negotiated_price:null,notes:null})});setSelectedQuote(await apiFetch<Quote>(`/procurement-ops/quotes/${selectedQuote.id}`));await load()}catch(e:any){setError(e?.message||"Unable to add quote item.")}}
 async function removeQuoteItem(id:string){if(!selectedQuote||!confirm("Remove quote item?"))return;try{await apiFetch(`/procurement-ops/quotes/${selectedQuote.id}/items/${id}`,{method:"DELETE"});setSelectedQuote(await apiFetch<Quote>(`/procurement-ops/quotes/${selectedQuote.id}`));await load()}catch(e:any){setError(e?.message||"Unable to remove quote item.")}}
 async function addCert(){const sid=supplierId();if(!sid)return;const type=prompt("Certification type","ISO / Compliance");if(!type)return;const expiry=prompt("Expiry date YYYY-MM-DD","");try{await apiFetch("/procurement-ops/certifications",{method:"POST",body:JSON.stringify({supplier_id:sid,certification_type:type,expiry_date:expiry||null,status:"valid",notes:null})});setSuccess("Certification created.");await load()}catch(e:any){setError(e?.message||"Unable to create certification.")}}
 async function editCert(c:Cert){const st=prompt("Status: valid, expired, expiring_soon, revoked",c.status);if(!st)return;try{await apiFetch(`/procurement-ops/certifications/${c.id}`,{method:"PUT",body:JSON.stringify({status:st})});setSuccess("Certification updated.");await load()}catch(e:any){setError(e?.message||"Unable to update certification.")}}
 async function revokeCert(c:Cert){if(!confirm("Revoke this certification?"))return;try{await apiFetch(`/procurement-ops/certifications/${c.id}`,{method:"DELETE"});setSuccess("Certification revoked.");await load()}catch(e:any){setError(e?.message||"Unable to revoke certification.")}}
 async function addProduction(){const poi=prompt("Purchase Order Item ID (blank allowed)",poItems[0]?.id||"");const sid=prompt("Supplier ID (blank allowed)",suppliers[0]?.id||"");const iid=prompt("Item ID (blank allowed)",items[0]?.id||"");const stage=prompt("Production stage","planning");if(!poi&&!sid&&!iid)return;try{await apiFetch("/procurement-ops/production-runs",{method:"POST",body:JSON.stringify({purchase_order_item_id:poi||null,supplier_id:sid||null,item_id:iid||null,production_stage:stage||"planning",priority:"medium"})});setSuccess("Production run created.");await load()}catch(e:any){setError(e?.message||"Unable to create production run.")}}
 async function editProduction(p:Prod){const stage=prompt("Production stage",p.production_stage);if(!stage)return;const milestone=prompt("Next milestone",p.next_milestone||"");try{await apiFetch(`/procurement-ops/production-runs/${p.id}`,{method:"PUT",body:JSON.stringify({production_stage:stage,next_milestone:milestone||null})});setSuccess("Production run updated.");await load()}catch(e:any){setError(e?.message||"Unable to update production run.")}}
 async function addQC(){const iid=itemId();if(!iid)return;const inspector=prompt("Inspector employee ID (blank allowed)",employees[0]?.id||"");const result=prompt("QC result: pending, pass, fail, conditional_pass","pending");try{await apiFetch("/procurement-ops/qc-inspections",{method:"POST",body:JSON.stringify({item_id:iid,inspector_employee_id:inspector||null,qc_result:result||"pending",follow_up_needed:false})});setSuccess("QC inspection created.");await load()}catch(e:any){setError(e?.message||"Unable to create QC inspection.")}}
 async function editQC(q:QC){const result=prompt("QC result: pending, pass, fail, conditional_pass",q.qc_result||"pending");if(!result)return;const actions=prompt("Actions required",q.actions_required||"");try{await apiFetch(`/procurement-ops/qc-inspections/${q.id}`,{method:"PUT",body:JSON.stringify({qc_result:result,actions_required:actions||null})});setSuccess("QC inspection updated.");await load()}catch(e:any){setError(e?.message||"Unable to update QC inspection.")}}
 async function addComm(){const sid=supplierId();if(!sid)return;const channel=prompt("Channel","email");const subject=prompt("Subject","Supplier follow-up");const notes=prompt("Notes","");try{await apiFetch("/procurement-ops/communications",{method:"POST",body:JSON.stringify({supplier_id:sid,channel:channel||null,subject:subject||null,notes:notes||null})});setSuccess("Supplier communication logged.");await load()}catch(e:any){setError(e?.message||"Unable to log communication.")}}
 async function editComm(c:Comm){const subject=prompt("Subject",c.subject||"");if(subject===null)return;const notes=prompt("Notes",c.notes||"");try{await apiFetch(`/procurement-ops/communications/${c.id}`,{method:"PUT",body:JSON.stringify({subject:subject||null,notes:notes||null})});setSuccess("Communication updated.");await load()}catch(e:any){setError(e?.message||"Unable to update communication.")}}
 async function deleteComm(c:Comm){if(!confirm("Delete this communication log?"))return;try{await apiFetch(`/procurement-ops/communications/${c.id}`,{method:"DELETE"});setSuccess("Communication deleted.");await load()}catch(e:any){setError(e?.message||"Unable to delete communication.")}}
 const addAction=tab==="quotes"?addQuote:tab==="certifications"?addCert:tab==="production"?addProduction:tab==="qc"?addQC:addComm;
 return <><div className="page-header"><div><div className="eyebrow">Procurement</div><h1 className="page-title">Procurement Operations</h1><p className="page-copy">Quotes, certifications, production, QC and supplier communication in one workspace.</p></div><div style={{display:"flex",gap:8}}><button className="btn btn-secondary" onClick={load}><RefreshCw size={15}/>Refresh</button><button className="btn btn-primary" onClick={addAction}><Plus size={15}/>Add {tab==="qc"?"QC Inspection":labelize(tab.slice(0,-(tab.endsWith("s")?1:0)))}</button></div></div><Message error={error} success={success}/><div className="card" style={{padding:8,display:"flex",gap:6,flexWrap:"wrap",marginBottom:14}}>{(["quotes","certifications","production","qc","communications"] as Tab[]).map(t=><button key={t} className={`btn ${tab===t?"btn-primary":"btn-ghost"}`} onClick={()=>setTab(t)}>{t==="qc"?"QC Inspections":t==="production"?"Production Runs":labelize(t)}</button>)}</div>
 {tab==="quotes"&&<div className="table-wrap"><table><thead><tr><th>Quote</th><th>Supplier</th><th>Date</th><th>Valid Until</th><th>Status</th><th>Actions</th></tr></thead><tbody>{quotes.length===0?<EmptyRow columns={6}/>:quotes.map(q=><tr key={q.id}><td><strong>{q.quote_number}</strong></td><td>{q.supplier_name}</td><td>{q.quote_date||"—"}</td><td>{q.valid_until||"—"}</td><td><StatusBadge value={q.status}/></td><td><div className="record-actions"><button className="record-action view" onClick={()=>viewQuote(q)}><Eye size={14}/></button><button className="record-action edit" onClick={()=>editQuote(q)}><Pencil size={14}/></button></div></td></tr>)}</tbody></table></div>}
 {tab==="certifications"&&<div className="table-wrap"><table><thead><tr><th>Supplier</th><th>Certification</th><th>Issue</th><th>Expiry</th><th>Status</th><th>Actions</th></tr></thead><tbody>{certs.length===0?<EmptyRow columns={6}/>:certs.map(c=><tr key={c.id}><td>{c.supplier_name}</td><td>{c.certification_type}</td><td>{c.issue_date||"—"}</td><td>{c.expiry_date||"—"}</td><td><StatusBadge value={c.status}/></td><td><div className="record-actions"><button className="record-action edit" onClick={()=>editCert(c)}><Pencil size={14}/></button>{isManager&&c.status!=="revoked"&&<button className="record-action delete" onClick={()=>revokeCert(c)}><Trash2 size={14}/></button>}</div></td></tr>)}</tbody></table></div>}
 {tab==="production"&&<div className="table-wrap"><table><thead><tr><th>Item</th><th>Supplier</th><th>Stage</th><th>Priority</th><th>Estimated</th><th>Milestone</th><th>Action</th></tr></thead><tbody>{production.length===0?<EmptyRow columns={7}/>:production.map(p=><tr key={p.id}><td>{p.item_name||"—"}</td><td>{p.supplier_name||"—"}</td><td><StatusBadge value={p.production_stage}/></td><td>{labelize(p.priority)}</td><td>{p.estimated_completion||"—"}</td><td>{p.next_milestone||"—"}</td><td><button className="record-action edit" onClick={()=>editProduction(p)}><Pencil size={14}/></button></td></tr>)}</tbody></table></div>}
 {tab==="qc"&&<div className="table-wrap"><table><thead><tr><th>Inspection</th><th>Item</th><th>Supplier</th><th>Inspector</th><th>Result</th><th>Follow Up</th><th>Action</th></tr></thead><tbody>{qc.length===0?<EmptyRow columns={7}/>:qc.map(q=><tr key={q.id}><td><strong>{q.inspection_number}</strong></td><td>{q.item_name||"—"}</td><td>{q.supplier_name||"—"}</td><td>{q.inspector_name||"—"}</td><td><StatusBadge value={q.qc_result}/></td><td>{q.follow_up_needed?"Yes":"No"}</td><td><button className="record-action edit" onClick={()=>editQC(q)}><Pencil size={14}/></button></td></tr>)}</tbody></table></div>}
 {tab==="communications"&&<div className="table-wrap"><table><thead><tr><th>Supplier</th><th>Time</th><th>Channel</th><th>Subject</th><th>Notes</th><th>Actions</th></tr></thead><tbody>{communications.length===0?<EmptyRow columns={6}/>:communications.map(c=><tr key={c.id}><td>{c.supplier_name}</td><td>{new Date(c.occurred_at).toLocaleString()}</td><td>{c.channel||"—"}</td><td>{c.subject||"—"}</td><td>{c.notes||"—"}</td><td><div className="record-actions"><button className="record-action edit" onClick={()=>editComm(c)}><Pencil size={14}/></button><button className="record-action delete" onClick={()=>deleteComm(c)}><Trash2 size={14}/></button></div></td></tr>)}</tbody></table></div>}
 {selectedQuote&&<Modal title={selectedQuote.quote_number} eyebrow="Supplier Quote" onClose={()=>setSelectedQuote(null)} width={900}><DetailGrid rows={[["Supplier",selectedQuote.supplier_name],["Date",selectedQuote.quote_date||"—"],["Valid Until",selectedQuote.valid_until||"—"],["Status",<StatusBadge value={selectedQuote.status}/>],["Notes",selectedQuote.notes||"—"]]}/><div className="panel-head" style={{marginTop:22}}><h3>Quote Items</h3><button className="btn btn-secondary" onClick={addQuoteItem}><Plus size={14}/>Add Item</button></div><div className="table-wrap"><table><thead><tr><th>Item</th><th>MOQ</th><th>Quoted</th><th>Negotiated</th><th>Action</th></tr></thead><tbody>{selectedQuote.items.length===0?<EmptyRow columns={5}/>:selectedQuote.items.map(i=><tr key={i.id}><td>{i.item_code} — {i.item_name}</td><td>{i.moq??"—"}</td><td>{money(i.quoted_price,selectedQuote.currency_code)}</td><td>{money(i.negotiated_price,selectedQuote.currency_code)}</td><td><button className="record-action delete" onClick={()=>removeQuoteItem(i.id)}><Trash2 size={14}/></button></td></tr>)}</tbody></table></div></Modal>}
 <GlobalSpinStyle/></>;
}

export default function Page() {
  return (
    <RequirePermission perm="procurement_ops.view">
      <ProcurementPage />
    </RequirePermission>
  );
}
