// This file is generated automatically by Next.js
// Do not edit this file manually
// This file validates that all pages and layouts export the correct types

import type { AppRoutes, LayoutRoutes, ParamMap } from "./routes.js"
import type { ResolvingMetadata, ResolvingViewport } from "next/types.js"

type AppPageConfig<Route extends AppRoutes = AppRoutes> = {
  default: React.ComponentType<{ params: Promise<ParamMap[Route]> } & any> | ((props: { params: Promise<ParamMap[Route]> } & any) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type LayoutConfig<Route extends LayoutRoutes = LayoutRoutes> = {
  default: React.ComponentType<LayoutProps<Route>> | ((props: LayoutProps<Route>) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}


// Validate ../../app/dashboard/ai/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/ai">> = Specific
  const handler = {} as typeof import("../../app/dashboard/ai/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/containers/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/containers">> = Specific
  const handler = {} as typeof import("../../app/dashboard/containers/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/customers/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/customers">> = Specific
  const handler = {} as typeof import("../../app/dashboard/customers/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/documents/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/documents">> = Specific
  const handler = {} as typeof import("../../app/dashboard/documents/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/ebay/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/ebay">> = Specific
  const handler = {} as typeof import("../../app/dashboard/ebay/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/employees/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/employees">> = Specific
  const handler = {} as typeof import("../../app/dashboard/employees/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/inventory/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/inventory">> = Specific
  const handler = {} as typeof import("../../app/dashboard/inventory/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/meta/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/meta">> = Specific
  const handler = {} as typeof import("../../app/dashboard/meta/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/new-items/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/new-items">> = Specific
  const handler = {} as typeof import("../../app/dashboard/new-items/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard">> = Specific
  const handler = {} as typeof import("../../app/dashboard/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/parts/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/parts">> = Specific
  const handler = {} as typeof import("../../app/dashboard/parts/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/payments/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/payments">> = Specific
  const handler = {} as typeof import("../../app/dashboard/payments/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/procurement/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/procurement">> = Specific
  const handler = {} as typeof import("../../app/dashboard/procurement/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/purchases/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/purchases">> = Specific
  const handler = {} as typeof import("../../app/dashboard/purchases/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/sales/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/sales">> = Specific
  const handler = {} as typeof import("../../app/dashboard/sales/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/settings/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/settings">> = Specific
  const handler = {} as typeof import("../../app/dashboard/settings/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/shipments/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/shipments">> = Specific
  const handler = {} as typeof import("../../app/dashboard/shipments/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/shopify/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/shopify">> = Specific
  const handler = {} as typeof import("../../app/dashboard/shopify/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/suppliers/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/suppliers">> = Specific
  const handler = {} as typeof import("../../app/dashboard/suppliers/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/tasks/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/tasks">> = Specific
  const handler = {} as typeof import("../../app/dashboard/tasks/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/tiktok/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/tiktok">> = Specific
  const handler = {} as typeof import("../../app/dashboard/tiktok/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/vehicles/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/vehicles">> = Specific
  const handler = {} as typeof import("../../app/dashboard/vehicles/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/login/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/login">> = Specific
  const handler = {} as typeof import("../../app/login/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/">> = Specific
  const handler = {} as typeof import("../../app/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/signup/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/signup">> = Specific
  const handler = {} as typeof import("../../app/signup/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}







// Validate ../../app/dashboard/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/dashboard">> = Specific
  const handler = {} as typeof import("../../app/dashboard/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../app/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}
