"use client";

import { Eye, Loader2, Pencil, Plus, RefreshCw, Search, Trash2 } from "lucide-react";
import { FormEvent, useCallback, useEffect, useMemo, useState } from "react";

import { DetailGrid, EmptyRow, Field, GlobalSpinStyle, LoadingRow, Message, Modal, SelectField, StatusBadge, TextAreaField, labelize } from "@/components/RealUi";
import { RequirePermission } from "@/components/RequirePermission";
import { CurrentUser, apiFetch, getCurrentUser } from "@/lib/api";

type ShipmentPO={id:string;po_number:string;supplier_name:string;status:string;order_total:number|string};
type ShipmentContainer={id:string;container_id:string;container_number:string;container_type:string|null;seal_number:string|null;actual_cbm:number|string|null;status:string;item_count:number;total_quantity:number|string};
type Shipment={id:string;business_unit_id:string;shipment_number:string;shipment_type:string;tracking_number:string|null;carrier:string|null;vessel_shipping_line:string|null;origin:string|null;destination:string|null;loading_date:string|null;ship_date:string|null;eta:string|null;arrival_date:string|null;status:string;total_cbm:number|string|null;customs_status:string|null;notes:string|null;purchase_orders:ShipmentPO[];containers:ShipmentContainer[];created_at:string;updated_at:string};
type ListResponse={total:number;offset:number;limit:number;items:Shipment[]};
type POLookup={id:string;po_number:string;supplier_name:string;status:string};
type ContainerLookup={id:string;container_number:string;container_type:string|null};
type ItemLookup={id:string;item_code:string;name:string};
type POItemLookup={id:string;purchase_order_id:string;po_number:string;item_id:string;item_name:string};
type ContainerItem={id:string;shipment_container_id:string;item_id:string;item_code:string;item_name:string;purchase_order_item_id:string|null;quantity:number|string;notes:string|null};
const statuses=["planned","booked","loading","in_transit","customs","arrived","delivered","delayed","cancelled"];
const types=["inbound","outbound","transfer"];
const empty={shipment_type:"inbound",tracking_number:"",carrier:"",vessel_shipping_line:"",origin:"",destination:"",loading_date:"",ship_date:"",eta:"",arrival_date:"",status:"planned",total_cbm:"",customs_status:"",notes:""};

function ShipmentsPage(){
 const [rows,setRows]=useState<Shipment[]>([]);const [poLookup,setPoLookup]=useState<POLookup[]>([]);const [containerLookup,setContainerLookup]=useState<ContainerLookup[]>([]);const [itemLookup,setItemLookup]=useState<ItemLookup[]>([]);const [poItemLookup,setPoItemLookup]=useState<POItemLookup[]>([]);const [user,setUser]=useState<CurrentUser|null>(null);const [search,setSearch]=useState("");const [statusFilter,setStatusFilter]=useState("");const [typeFilter,setTypeFilter]=useState("");const [loading,setLoading]=useState(true);const [error,setError]=useState("");const [success,setSuccess]=useState("");const [mode,setMode]=useState<"create"|"view"|"edit"|null>(null);const [selected,setSelected]=useState<Shipment|null>(null);const [form,setForm]=useState(empty);const [saving,setSaving]=useState(false);const [containerItems,setContainerItems]=useState<Record<string,ContainerItem[]>>({});
 const isManager=useMemo(()=>{const r=new Set((user?.roles||[]).map(x=>x.toLowerCase()));return r.has("manager")||r.has("administrator")},[user]);
 const load=useCallback(async()=>{setLoading(true);try{const p=new URLSearchParams();if(search.trim())p.set("search",search.trim());if(statusFilter)p.set("shipment_status",statusFilter);if(typeFilter)p.set("shipment_type",typeFilter);p.set("limit","300");const r=await apiFetch<ListResponse>(`/shipments?${p}`);setRows(r.items)}catch(e:any){setError(e?.message||"Unable to load shipments.")}finally{setLoading(false)}},[search,statusFilter,typeFilter]);
 useEffect(()=>{Promise.all([apiFetch<POLookup[]>("/shipments/lookups/purchase-orders"),apiFetch<ContainerLookup[]>("/shipments/lookups/containers"),apiFetch<ItemLookup[]>("/procurement-ops/lookups/items"),apiFetch<POItemLookup[]>("/procurement-ops/lookups/purchase-order-items"),getCurrentUser()]).then(([p,c,i,pi,u])=>{setPoLookup(p);setContainerLookup(c);setItemLookup(i);setPoItemLookup(pi);setUser(u)}).catch(()=>{})},[]);useEffect(()=>{const t=setTimeout(load,250);return()=>clearTimeout(t)},[load]);
 function setField(k:keyof typeof empty,v:string){setForm(f=>({...f,[k]:v}))}
 function create(){setSelected(null);setForm(empty);setMode("create")}
 async function refreshDetail(id:string){const d=await apiFetch<Shipment>(`/shipments/${id}`);setSelected(d);return d}
 async function open(row:Shipment,target:"view"|"edit"){setMode(target);try{const d=await refreshDetail(row.id);setForm({shipment_type:d.shipment_type,tracking_number:d.tracking_number||"",carrier:d.carrier||"",vessel_shipping_line:d.vessel_shipping_line||"",origin:d.origin||"",destination:d.destination||"",loading_date:d.loading_date||"",ship_date:d.ship_date||"",eta:d.eta||"",arrival_date:d.arrival_date||"",status:d.status,total_cbm:d.total_cbm!=null?String(d.total_cbm):"",customs_status:d.customs_status||"",notes:d.notes||""});if(target==="view"){const entries=await Promise.all(d.containers.map(async c=>[c.id,await apiFetch<ContainerItem[]>(`/shipments/${d.id}/containers/${c.id}/items`)] as const));setContainerItems(Object.fromEntries(entries))}}catch(e:any){setError(e?.message||"Unable to load shipment.");setMode(null)}}
 async function save(e:FormEvent){e.preventDefault();setSaving(true);setError("");const payload={shipment_type:form.shipment_type,tracking_number:form.tracking_number||null,carrier:form.carrier||null,vessel_shipping_line:form.vessel_shipping_line||null,origin:form.origin||null,destination:form.destination||null,loading_date:form.loading_date||null,ship_date:form.ship_date||null,eta:form.eta||null,arrival_date:form.arrival_date||null,status:form.status,total_cbm:form.total_cbm?Number(form.total_cbm):null,customs_status:form.customs_status||null,notes:form.notes||null};try{if(mode==="create"){await apiFetch("/shipments",{method:"POST",body:JSON.stringify({...payload,purchase_order_ids:[]})});setSuccess("Shipment created.")}else if(selected){await apiFetch(`/shipments/${selected.id}`,{method:"PUT",body:JSON.stringify(payload)});setSuccess("Shipment updated.")}await load();setMode(null)}catch(e:any){setError(e?.message||"Unable to save shipment.")}finally{setSaving(false)}}
 async function cancel(row:Shipment){if(!confirm(`Cancel ${row.shipment_number}?`))return;try{await apiFetch(`/shipments/${row.id}`,{method:"DELETE"});setSuccess("Shipment cancelled.");await load()}catch(e:any){setError(e?.message||"Unable to cancel shipment.")}}
 async function linkPO(){if(!selected)return;const choices=poLookup.filter(p=>!selected.purchase_orders.some(x=>x.id===p.id));const id=prompt("Purchase Order ID",choices[0]?.id||"");if(!id)return;try{await apiFetch(`/shipments/${selected.id}/purchase-orders/${id}`,{method:"POST"});await open(selected,"view")}catch(e:any){setError(e?.message||"Unable to link PO.")}}
 async function unlinkPO(id:string){if(!selected||!confirm("Unlink this PO?"))return;try{await apiFetch(`/shipments/${selected.id}/purchase-orders/${id}`,{method:"DELETE"});await open(selected,"view")}catch(e:any){setError(e?.message||"Unable to unlink PO.")}}
 async function linkContainer(){if(!selected)return;const choices=containerLookup.filter(c=>!selected.containers.some(x=>x.container_id===c.id));const id=prompt("Container ID",choices[0]?.id||"");if(!id)return;const seal=prompt("Seal number","");try{await apiFetch(`/shipments/${selected.id}/containers`,{method:"POST",body:JSON.stringify({container_id:id,seal_number:seal||null,actual_cbm:null,status:"planned"})});await open(selected,"view")}catch(e:any){setError(e?.message||"Unable to link container.")}}
 async function unlinkContainer(sc:ShipmentContainer){if(!selected||!confirm("Detach this container? Container items must be removed first."))return;try{await apiFetch(`/shipments/${selected.id}/containers/${sc.id}`,{method:"DELETE"});await open(selected,"view")}catch(e:any){setError(e?.message||"Unable to detach container.")}}
 async function updateContainer(sc:ShipmentContainer){if(!selected)return;const st=prompt("Container status",sc.status);if(!st)return;const cbm=prompt("Actual CBM",sc.actual_cbm!=null?String(sc.actual_cbm):"");try{await apiFetch(`/shipments/${selected.id}/containers/${sc.id}`,{method:"PUT",body:JSON.stringify({status:st,actual_cbm:cbm?Number(cbm):null})});await open(selected,"view")}catch(e:any){setError(e?.message||"Unable to update shipment container.")}}
 async function addContainerItem(sc:ShipmentContainer){if(!selected)return;const itemId=prompt("Catalog item ID",itemLookup[0]?.id||"");if(!itemId)return;const linkedPoIds=new Set(selected.purchase_orders.map(p=>p.id));const pi=poItemLookup.find(p=>p.item_id===itemId&&linkedPoIds.has(p.purchase_order_id));const qty=Number(prompt("Quantity","1")||0);try{await apiFetch(`/shipments/${selected.id}/containers/${sc.id}/items`,{method:"POST",body:JSON.stringify({item_id:itemId,purchase_order_item_id:pi?.id||null,quantity:qty,notes:"Added from dashboard"})});await open(selected,"view")}catch(e:any){setError(e?.message||"Unable to add container item.")}}
 async function removeContainerItem(sc:ShipmentContainer,ci:ContainerItem){if(!selected||!confirm(`Remove ${ci.item_name}?`))return;try{await apiFetch(`/shipments/${selected.id}/containers/${sc.id}/items/${ci.id}`,{method:"DELETE"});await open(selected,"view")}catch(e:any){setError(e?.message||"Unable to remove container item.")}}

 return <><div className="page-header"><div><div className="eyebrow">Logistics</div><h1 className="page-title">Shipments</h1><p className="page-copy">Track inbound, outbound and transfer shipments with POs and containers.</p></div><div style={{display:"flex",gap:8}}><button className="btn btn-secondary" onClick={load}><RefreshCw size={15}/>Refresh</button><button className="btn btn-primary" onClick={create}><Plus size={15}/>Add Shipment</button></div></div><Message error={error} success={success}/><div className="records-toolbar card"><div><strong>All Shipments</strong><div className="muted" style={{fontSize:12}}>{rows.length} visible</div></div><div style={{display:"flex",gap:8,flexWrap:"wrap"}}><div className="records-search"><Search size={15}/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Shipment, tracking, carrier..."/></div><select className="select" style={{width:150}} value={typeFilter} onChange={e=>setTypeFilter(e.target.value)}><option value="">All types</option>{types.map(t=><option key={t} value={t}>{labelize(t)}</option>)}</select><select className="select" style={{width:155}} value={statusFilter} onChange={e=>setStatusFilter(e.target.value)}><option value="">All statuses</option>{statuses.map(s=><option key={s} value={s}>{labelize(s)}</option>)}</select></div></div><div className="table-wrap"><table><thead><tr><th>Shipment</th><th>Type</th><th>Carrier</th><th>Route</th><th>ETA</th><th>Tracking</th><th>Status</th><th>Actions</th></tr></thead><tbody>{loading?<LoadingRow columns={8}/>:rows.length===0?<EmptyRow columns={8}/>:rows.map(r=><tr key={r.id}><td><strong>{r.shipment_number}</strong></td><td>{labelize(r.shipment_type)}</td><td>{r.carrier||r.vessel_shipping_line||"—"}</td><td>{[r.origin,r.destination].filter(Boolean).join(" → ")||"—"}</td><td>{r.eta||"—"}</td><td>{r.tracking_number||"—"}</td><td><StatusBadge value={r.status}/></td><td><div className="record-actions"><button className="record-action view" onClick={()=>open(r,"view")}><Eye size={14}/></button><button className="record-action edit" onClick={()=>open(r,"edit")}><Pencil size={14}/></button>{isManager&&r.status!=="cancelled"&&r.status!=="delivered"&&<button className="record-action delete" onClick={()=>cancel(r)}><Trash2 size={14}/></button>}</div></td></tr>)}</tbody></table></div>
 {(mode==="create"||mode==="edit")&&<Modal title={mode==="create"?"Create Shipment":`Edit ${selected?.shipment_number||"Shipment"}`} eyebrow="Logistics" onClose={()=>setMode(null)}><form onSubmit={save}><div className="form-grid"><SelectField label="Shipment Type" value={form.shipment_type} onChange={v=>setField("shipment_type",v)} options={types.map(v=>({value:v,label:labelize(v)}))}/><SelectField label="Status" value={form.status} onChange={v=>setField("status",v)} options={statuses.map(v=>({value:v,label:labelize(v)}))}/><Field label="Tracking Number" value={form.tracking_number} onChange={v=>setField("tracking_number",v)}/><Field label="Carrier" value={form.carrier} onChange={v=>setField("carrier",v)}/><Field label="Vessel / Shipping Line" value={form.vessel_shipping_line} onChange={v=>setField("vessel_shipping_line",v)}/><Field label="Origin" value={form.origin} onChange={v=>setField("origin",v)}/><Field label="Destination" value={form.destination} onChange={v=>setField("destination",v)}/><Field label="Loading Date" type="date" value={form.loading_date} onChange={v=>setField("loading_date",v)}/><Field label="Ship Date" type="date" value={form.ship_date} onChange={v=>setField("ship_date",v)}/><Field label="ETA" type="date" value={form.eta} onChange={v=>setField("eta",v)}/><Field label="Arrival Date" type="date" value={form.arrival_date} onChange={v=>setField("arrival_date",v)}/><Field label="Total CBM" type="number" min="0" step="0.01" value={form.total_cbm} onChange={v=>setField("total_cbm",v)}/><Field label="Customs Status" value={form.customs_status} onChange={v=>setField("customs_status",v)}/><TextAreaField label="Notes" value={form.notes} onChange={v=>setField("notes",v)}/></div><div style={{display:"flex",justifyContent:"flex-end",gap:8,marginTop:18}}><button type="button" className="btn btn-secondary" onClick={()=>setMode(null)}>Cancel</button><button className="btn btn-primary" disabled={saving}>{saving?<><Loader2 className="spin" size={15}/>Saving...</>:"Save Shipment"}</button></div></form></Modal>}
 {mode==="view"&&selected&&<Modal title={selected.shipment_number} eyebrow="Shipment Details" onClose={()=>setMode(null)} width={1100}><DetailGrid rows={[["Type",labelize(selected.shipment_type)],["Status",<StatusBadge value={selected.status}/>],["Tracking",selected.tracking_number||"—"],["Carrier",selected.carrier||"—"],["Origin",selected.origin||"—"],["Destination",selected.destination||"—"],["ETA",selected.eta||"—"],["Customs",selected.customs_status||"—"],["Total CBM",selected.total_cbm??"—"],["Notes",selected.notes||"—"]]}/><div className="panel-head" style={{marginTop:22}}><h3>Linked Purchase Orders</h3><button className="btn btn-secondary" onClick={linkPO}><Plus size={14}/>Link PO</button></div>{selected.purchase_orders.length===0?<div className="muted">No linked purchase orders.</div>:selected.purchase_orders.map(p=><div key={p.id} className="card" style={{padding:10,display:"flex",justifyContent:"space-between",marginBottom:8}}><span><strong>{p.po_number}</strong> · {p.supplier_name} · {labelize(p.status)}</span><button className="btn btn-ghost" onClick={()=>unlinkPO(p.id)}>Unlink</button></div>)}<div className="panel-head" style={{marginTop:22}}><h3>Containers</h3><button className="btn btn-secondary" onClick={linkContainer}><Plus size={14}/>Attach Container</button></div>{selected.containers.length===0?<div className="muted">No containers attached.</div>:selected.containers.map(sc=><div className="card" style={{padding:14,marginBottom:12}} key={sc.id}><div style={{display:"flex",alignItems:"center",justifyContent:"space-between",gap:10}}><div><strong>{sc.container_number}</strong><div className="muted" style={{fontSize:12}}>{sc.container_type||"Container"} · {labelize(sc.status)} · {Number(sc.total_quantity)} qty</div></div><div style={{display:"flex",gap:6}}><button className="btn btn-ghost" onClick={()=>updateContainer(sc)}>Update</button><button className="btn btn-ghost" onClick={()=>addContainerItem(sc)}>Add Item</button><button className="btn btn-ghost" onClick={()=>unlinkContainer(sc)}>Detach</button></div></div><div style={{marginTop:10}}>{(containerItems[sc.id]||[]).length===0?<div className="muted" style={{fontSize:12}}>No items loaded.</div>:(containerItems[sc.id]||[]).map(ci=><div key={ci.id} style={{display:"flex",justifyContent:"space-between",padding:"7px 0",borderTop:"1px solid var(--line)"}}><span>{ci.item_code} — {ci.item_name} · {Number(ci.quantity)}</span><button className="record-action delete" onClick={()=>removeContainerItem(sc,ci)}><Trash2 size={13}/></button></div>)}</div></div>)}</Modal>}
 <GlobalSpinStyle/></>;
}

export default function Page() {
  return (
    <RequirePermission perm="shipments.view">
      <ShipmentsPage />
    </RequirePermission>
  );
}
